name: Call Next.js API with Supabase Auth

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual execution

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Next.js API with Supabase Auth
        run: |
          curl -X POST "https://easy-dms.tillmbecker.com/api/keep-alive" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
